Update contributors list in CI
kaigionrails/conference-app pull request #98
Opened 2023-11-02 08:27 UTC by okuramasafumi

Or at least it's an attempt to do so.
I hope someone who's familiar with GItHub Actions would review it!

2023-11-02 17:14 UTC, unasuke commented on .github/workflows/update-contributors.yml
> +                                                                                                   /repos/kaigionrails/conference-app/contributors > contributors.json
Too many indentations?

2023-11-05 05:26 UTC, okuramasafumi commented on .github/workflows/update-contributors.yml
> +                                                                                                   /repos/kaigionrails/conference-app/contributors > contributors.json
Thx, fixed!

2023-11-05 05:43 UTC, unasuke approved these changes
looks yosasou

2023-11-05 05:44 UTC, unasuke requested changes
I found a bit concern

2023-11-05 06:05 UTC, unasuke approved these changes
yosasou again

2023-11-05 06:11 UTC, merged

2023-11-05 14:10 UTC, unasuke commented
ref #86